FROM golang:1.21-alpine AS builder

WORKDIR /app

# Сначала копируем файлы зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Затем копируем остальные файлы
COPY . .

# Отключаем CGO для более стабильной сборки
ENV CGO_ENABLED=0
RUN go build -o /bin/api cmd/smart-house-api/main.go

FROM alpine:3.18

RUN apk add --no-cache tzdata ca-certificates

WORKDIR /app
COPY --from=builder /bin/api /app/api
COPY configs/config.yaml /app/configs/config.yaml

EXPOSE 8080
CMD ["/app/api"]
