FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY . .

RUN go build -o /bin/bot cmd/smart-house-bot/main.go

FROM alpine:3.18

WORKDIR /app
COPY --from=builder /bin/bot /app/bot
COPY configs/config.yaml /app/configs/config.yaml

EXPOSE 9091
CMD ["/app/bot"]
