global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'collector'
    static_configs:
      - targets: ['collector:9090']

  - job_name: 'bot'
    metrics_path: /metrics
    static_configs:
      - targets: ['bot:9091']

  - job_name: 'emulator'
    metrics_path: /metrics
    static_configs:
      - targets: ['emulator:9092']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']